### ISSUE TITLE
Confusion about the quantitative results of baseline comparison

### ISSUE THREAD

**Issue by yijicheng** [facebookresearch/tava#10]
Thanks for your excellent work!

I rerun neuralbody and animatable-nerf following your evaluation setting. However, the results of them (psnr ranges from 20 to28) are all worse than table 6 in your paper.

I am confused about how you reproduce the high results?

**Comment by liruilong940607** [comment]
Hi our neuralbody experiments are here: https://github.com/liruilong940607/neuralbody/tree/submission

It is forked from the official repo and modified accordingly

**Comment by liruilong940607** [comment]
Also the animatable-nerf experiments: https://github.com/liruilong940607/animatable_nerf/tree/submission

**Comment by liruilong940607** [comment]
You can check out the github commit history to see what we changed.

**Comment by yijicheng** [comment]
Thank you so much~

**Comment by LaolangOne** [comment]
> Also the animatable-nerf experiments: https://github.com/liruilong940607/animatable_nerf/tree/submission

你好，我尝试运行了你修改过的animatable_nerf代码，按照TAVA的数据集分割方法，在CoreView_377上训练得到的psnr结果最终只有25.06，这与你在TAVA论文中的描述相差甚远，这是什么情况呢？
