### ISSUE TITLE
Is the PSNR/SSIM in paper calculated for the whole 512*512 image?

### ISSUE THREAD

**Issue by HelloRicky123** [facebookresearch/tava#13]
Hi,

Thanks for the code.

The quantitative result of Neural Body is higher than the original paper. I see in https://github.com/facebookresearch/tava/blob/a9576801e81aebcf242588be39315e27f915894e/tava/utils/evaluation.py#L70 that the mask is None. Could you let me know whether the PSNR/SSIM results in the original paper are calculated for the whole 512*512 image? In Neural Body, the authors calculated the PSNR/SSIM for the 2D bounding box, excluding the black background.

**Comment by liruilong940607** [comment]
Hey sorry for the late reply! I didn't track this repo's issue for a really long time.

To clarify, we didn't use the bounding box for any of the methods including Neural Body. So the metric is on the whole image.
