### ISSUE TITLE
Different results when changing the data loader type. 

### ISSUE THREAD

**Issue by coreqode** [facebookresearch/tava#5]
Hi again!!

Is there a reason you have used the `torch.utils.data.IterableDataset` rather than the `torch.utils.data.Dataset`? 
When I ported the code to the latter, training was much faster, but the results were not good. While in the case of the former (default), training is slower. 
Further what's the use case of `cache_n_repeat`[here.](https://github.com/facebookresearch/tava/blob/a9576801e81aebcf242588be39315e27f915894e/tava/datasets/abstract.py#L63)

**Comment by liruilong940607** [comment]
I believe `torch.utils.data.IterableDataset` is inherited from `torch.utils.data.Dataset` so there shouldn’t be a performance discrepancy. 

Cache is for reusing the same image for multiple iterations. I was having IO bottlenecks so just cache the image being load and repeatly sample rays in the sample image for multiple iterations. This is not ideal for performance but gave me some speedup during training

**Comment by liruilong940607** [comment]
Close for now as it seems the question is resolved.
