### ISSUE TITLE
Questions about baseline experiments

### ISSUE THREAD

**Issue by yijicheng** [facebookresearch/tava#6]
Thanks for your excellent work!

I am confused about how to compare tava and neuralbody?

Training dataset in the tava is different from original neuralbody. And dataset used in the neuralbody should be consecutive frames, because of the time-varing latent embedding.

So, in your paper, Is the training dataset of neuralbody be the same as the original one or the tava one?

**Comment by liruilong940607** [comment]
Hi we used the TAVA data split for neural body for fair comparison.

The per-frame latent code in neural body is disabled because it is not applicable to novel-pose synthesis (given a new pose there is no per-frame latent code that match with it)
