### ISSUE TITLE
Question about processing ZJU dataset

### ISSUE THREAD

**Issue by PeiLin-666** [facebookresearch/tava#9]
![118ae4b366ce6f658e7627d8fb9bc77](https://user-images.githubusercontent.com/25741106/197965122-07d123c2-eb3c-42f3-a8ea-1d23f06fc0b3.png)
In tools/process_zju/lbs.py, what is the purpose to calculate the error between the posed joints and the joints in rest? Why are the first 3 joints?

**Comment by Xiaoming-Zhao** [comment]
I guess it is because that for ZJU's dataset, their SMPL params have the first 3 elements to be zeros, see [here](https://github.com/zju3dv/neuralbody#potential-problems-of-provided-smpl-parameters). This is a sanity check specifically for ZJU's dataset. It does not hold for general SMPL params.

**Comment by PeiLin-666** [comment]
> 

Yes. If the first 3 elements denote the position of root joint (x,y,z), it will be easy to explain. However, in this case, it takes the first three joints into consideration.

**Comment by Xiaoming-Zhao** [comment]
The first three joints after the root joint, namely joint 1-3, are rigidly-attached to the root joint. Therefore, if the root joint does not move, those 3 joints will not move either. These lines want to check this.

**Comment by PeiLin-666** [comment]
> The first three joints after the root joint, namely joint 1-3, are rigidly-attached to the root joint. Therefore, if the root joint does not move, those 3 joints will not move either. These lines want to check this.

Get it! Thank you!
